// Uncomment the controller you'd like to try out regardin SOQL injection in reference to the security section of the write up. 
//LightningDatatableController.getContacts('001fL000005viPeQAI', 'lightning', '', 25);

//LightningDatatableControllerEIL.getContacts('001fL000005viPeQAI', 'lightning', '', 25);

//LightningDatatableControllerEscapeMethod.getContacts('001fL000005viPeQAI', 'lightning', '', 25);